name: crypto_currency_converter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  dio: ^5.0.1
  either_dart: ^0.3.0
  bottom_sheet: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # JSON parsing
  build_runner: ^2.1.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
